### ISSUE TITLE
We need a linter to meet my silly requirements

### ISSUE THREAD

**Issue by turt2live** [turt2live/synapse-netcore-workers#10]
For some reason I'm very nitpicky about C# code, so a relatively strict linter is required. Assigning to myself because I'm probably the worst person for having opinions.

**Comment by Half-Shot** [comment]
*looks up from his masterpiece of mixing styles* uh oh

**Comment by turt2live** [comment]
Done in https://github.com/turt2live/synapse-netcore-workers/commit/fe6b615a3506608e50e76e910ec9867b0aa1bb00
